# Generated by Django 5.1.1 on 2024-11-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(default="", max_length=50),
        ),
    ]
