# Generated by Django 5.1.1 on 2024-10-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("header", models.CharField(max_length=100, verbose_name="Заголовок поста")),
                ("content", models.CharField(max_length=1000, verbose_name="Описание")),
                ("image", models.ImageField(upload_to="photos/", verbose_name="Изображение")),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                ("is_active", models.BooleanField(default=True)),
                ("quantity", models.IntegerField(default=0, verbose_name="Количество просмотров")),
            ],
        ),
    ]
