# Generated by Django 5.1.1 on 2024-10-28 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_like_photo", "0002_alter_post_options_alter_post_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="quantity",
            new_name="views_count",
        ),
    ]
