# Generated by Django 5.1.1 on 2024-10-22 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_category_options_alter_contact_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image",
        ),
    ]
