# Generated by Django 5.1.1 on 2024-11-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_delete_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "продукт", "verbose_name_plural": "продукты"},
        ),
    ]
