# Generated by Django 5.1.1 on 2024-11-24 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_product_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="owner",
        ),
    ]
